### ISSUE TITLE
results are not filtered properly

### ISSUE THREAD

**Issue by jaapjorisjaap** [UUDigitalHumanitieslab/gretel#104]
When applying a filter in the xpath query the filter is not applied properly. For example: When applying the uttid range a bigger range gives less results.

**Comment by oktaal** [comment]
The problem was that a string comparison is done rather than a numerical comparison. 28405d82a121844c7f3e7363045f16ecaaa5795c fixes that. However, it will not work for dates. Then again, the previous code didn't work for dates either anyway.
