### ISSUE TITLE
Add a tooltip component

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/gretel#138]
Currently plain `title` attributes are used. Those do not support additional markup and don't display as quickly as tooltip on hover. https://ng-bootstrap.github.io/#/components/tooltip/examples

**Comment by JeltevanBoheemen** [comment]
@oktaal I've got working tooltips with the module you've linked. However I've noticed we are using Bulma over Bootstrap in Gretel currently. Is it wise to introduce another styling package? Or do you have negative experience with Bulma tooltips? (https://wikiki.github.io/elements/tooltip/)

**Comment by oktaal** [comment]
Bulma-tooltip doesn't support HTML markup either: the tooltip content is specified in a `data-tooltip` attribute.

**Comment by JeltevanBoheemen** [comment]
Right, good observation. I'll go with the bootstrap one then.

**Comment by oktaal** [comment]
Well I'm not quite sure why I specified that one! In https://github.com/UUDigitalHumanitieslab/I-analyzer/tree/develop/web-ui/src/app [Balloon.css](https://www.npmjs.com/package/balloon-css) is being used.

**Comment by JeltevanBoheemen** [comment]
Ok I'll dig into the options. Just wanted to know if you had a specific implementation in mind.
