### ISSUE TITLE
Tree tooltip overflows viewport

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/gretel#144]
Tree tooltips should stay within the viewport somehow. For example by automatically placing them in some other position (left/right) or moving them off center when needed.

![image](https://user-images.githubusercontent.com/24268578/43952885-841a8752-9c97-11e8-9b25-272f37e2c026.png)

**Comment by JeltevanBoheemen** [comment]
Related to #138

**Comment by oktaal** [comment]
Issue still exists after merging #155

**Comment by JeltevanBoheemen** [comment]
Not really related to #138.
