### ISSUE TITLE
Range filter can be dragged beyond limits

### ISSUE THREAD

**Issue by JeltevanBoheemen** [UUDigitalHumanitieslab/gretel#152]
![screen shot 2018-09-12 at 11 34 33](https://user-images.githubusercontent.com/4539142/45416272-daa2bc00-b67f-11e8-9227-1674369788f8.png)
![screen shot 2018-09-12 at 11 32 10](https://user-images.githubusercontent.com/4539142/45416205-a8915a00-b67f-11e8-9e78-cb4d7480e111.png)

In this case, the range filter does not offer any functionality anyway, so the best solution is probably to check for NaN in the range and display accordingly.

**Comment by oktaal** [comment]
Resolved by https://github.com/UUDigitalHumanitieslab/gretel/commit/02b2f6db047f108946c849a7b9ebe222b499ff1d
