### ISSUE TITLE
Create DOI for new software releases

### ISSUE THREAD

**Issue by kequach** [UUDigitalHumanitieslab/gretel#255]
I wanted to ask if you considered to create a DOI for the GrETEL search engine. This allows researchers to reference a version of GrETEL with ease and can be done with Zenodo for example. There is also great integration between Zenodo, which creates a new DOI and a persistent copy of the repository for each release, and Github. You can find instructions on how to create a DOI here from official Github docs: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content 

On a similar note, it also helps researchers to know how to correctly cite the software. I saw that you already have this information on the website but Github utilizes the citation file format which you can use in addition. You can find more information about it here: https://citation-file-format.github.io/ 
I would be happy to help with this if you have any questions.

**Comment by oktaal** [comment]
Resolved by a0ac90d817f8891f7cebe83f00dacff096f06ae4 We still have to look into integrating this with a better release flow, so this is always current with the version on the server.
