### ISSUE TITLE
Move basex data to separate server

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/gretel#49]
The ORAC server should be used for this, it has much more disk space and is currently basically idle.

**Comment by oktaal** [comment]
I've added the user `basex` to the ORAC server. The basex server can be started using the script `/etc/init.d/basex start`

```bash
#! /bin/sh

### BEGIN INIT INFO
# Provides:          basexserver
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: basex initscript
# Description:       basex
### END INIT INFO

BASEX=/usr/bin/basexserver
BASEX_USER=basex

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting BaseX server"
    su - deploy -c "$BASEX -S"
    ;;
  stop)
    echo "Stopping BaseX server"
    su - deploy -c "$BASEX stop"
    ;;
  *)
    echo "Usage: /etc/init.d/basex {start|stop}"
    exit 1
    ;;
esac
```

The existing databases are now moved to `/home/basex/BaseXData`.

**Comment by oktaal** [comment]
It's up and running now. Switched off the BaseX server on the gretel server. Let's see if this will remain operational, then I'll remove the data from the gretel server somewhere next week.

**Comment by oktaal** [comment]
Also removed the BaseX data from the Gretel server now.

**Comment by oktaal** [comment]
@jgonggrijp can you review this?

**Comment by jgonggrijp** [comment]
If by "this" you mean your posts in this issue ticket, then I don't see any problem. Two caveats:

 1. My experience with init.d is very limited.
 2. My efforts with init.d were only partially successful.
