### ISSUE TITLE
Redirect to PHP from Angular

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/gretel#64]

**Comment by jgonggrijp** [comment]
??? #63

**Comment by oktaal** [comment]
Newer interface stuff in GrETEL and modification/rework (for example of the results page) will be done in Angular. A simple redirect is needed that way and back (#63) to allow the current functionality to still be accessible for the user. The current interface is mostly created using a combination of server-side PHP and JavaScript.

**Comment by jgonggrijp** [comment]
Ah, that explains. 👍
