### ISSUE TITLE
Download results in Angular

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/gretel#66]

**Comment by jaapjorisjaap** [comment]
- Have a limit of numbers of result
- Create txt server side (with api call to results)
- Make clear the results in table are a subset of the whole set.

**Comment by oktaal** [comment]
The reason for creating the results server side is because this allows for directly streaming the results to the user. This way there is no memory limit on the size of the results file. This is unfortunately not possible in JavaScript (at least not when outputting to a file to download), because then everything needs to be concatenated into a single blob object.
