### ISSUE TITLE
Feature equivalent results in Angular

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/gretel#68]

**Comment by jaapjorisjaap** [comment]
- hidden not known issues

**Comment by jgonggrijp** [comment]
This sounds completely mystical.

**Comment by oktaal** [comment]
Basically this is to deal with converting functionality that exists in the current result page but which we are not yet (fully) aware of.

**Comment by oktaal** [comment]
Selecting components also needs to be added.
