### ISSUE TITLE
Live filter results in Angular

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/gretel#69]
Changing filters should trigger the results being updated without having to reload the whole page as is currently done. The route should be updated with this information (similar to how this is done in I-analyzer), so the user can also use the browser history to go back and forth through the applied filters.

**Comment by jaapjorisjaap** [comment]
- stub implementation of a filter dropwdown menu
- Apply filter server side
- update query

**Comment by oktaal** [comment]
Stub: first have hard coded filter values.
