### ISSUE TITLE
Results are duplicated up to the search limit

### ISSUE THREAD

**Issue by jaapjorisjaap** [UUDigitalHumanitieslab/gretel#86]
ResultsService.results is able to get unlimited amount of results out of the api.
Looks like it is not limited to the 500 results

**Comment by oktaal** [comment]
I didn't actually fix the issue. In `treebank-search.php` the `$endPosIteration` is multiplied with the `$flushLimit`, I mistakenly passed the offset into `$endPosIteration` now causing a multiplication of the search limit by the flush limit. Secondly, the search limit is only applied for each component. For each new component the position is reset to 0 again.
